version: "3.7"

services:
  stockapigateway:
    hostname: stockapigateway
    container_name: stockapigateway
    build:
      context: .
      dockerfile: .\StockMicroservices.APIGateway\Dockerfile
    networks:
      - stocknetwork
    ports:
      - "44323:80"
      - "44324:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=9001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Anderson@1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - stockapi

  rabbitmqservice:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    container_name: rabbitmq
    networks:
      - stocknetwork
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  stockidentityserver:
    build:
      context: .
      dockerfile: .\StockMicroservices.IdentityServer\Dockerfile
    ports:
      - "44312:80"
      - "44313:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Anderson@1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

  stockapi:
    build:
      context: .
      dockerfile: .\StockMicroservices.API\Dockerfile
    hostname: stockapi
    container_name: stockapi
    networks:
      - stocknetwork
    ports:
      - "44376:80"
      - "44377:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=6001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Anderson@1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - rabbitmqservice

  stockwebclient:
    build:
      context: .
      dockerfile: .\StockMicroservices.WebClient\ClientApp\Dockerfile
    networks:
      - stocknetwork
    ports:
      - "3000:3000"
    depends_on:
      - stockapigateway

  stockmarketupdater:
    build:
      context: .
      dockerfile: .\StockMicroservices.StockMarketUpdater\Dockerfile
    networks:
      - stocknetwork
    depends_on:
      - rabbitmqservice

networks:
  stocknetwork:
    driver: bridge
