version: '3.4'

services:
 
  grafana:
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./opentelemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  envoy:
    container_name: envoy
    restart: always
    hostname: envoy
    ports:
      - "45555:80"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    
  stockmicroservices.stockmarketupdater:
    container_name: stockmarketupdater
    depends_on:
      - rabbitmq
    environment:
      - RabbitMq:RetryCount=5
      - RabbitMq:Hostname=rabbitmq
      - RabbitMq:Username=user
      - RabbitMq:Password=password
    ports:
      - 44444:44444

  stockmicroservices.api:
    container_name: stockapi
    depends_on:
      - rabbitmq
      - stockmicroservices.identityserver
      - otel-collector
      - loki
      - prometheus
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - APIScope=StockMicroservicesAPI
      - IdentityServerUrl=http://stockidentityserver
      - RabbitMq:RetryCount=5
      - RabbitMq:Hostname=rabbitmq
      - RabbitMq:Username=user
      - RabbitMq:Password=password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=StockMicroservicesAPI
    ports:
      - "44300:80"

  stockmicroservices.apigateway:
    container_name: stockapigateway
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://stockidentityserver
      - APIScope=StockMicroservicesAPI
    ports:
      - "44405:80"
    depends_on:
      - stockmicroservices.api

  stockmicroservices.identityserver:
    container_name: stockidentityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
    ports:
      - "44401:80"
  

  stockmicroservices.webclient:
    container_name: stockwebclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLIENT_ID=client_id_react
      - AUTHORITY=http://localhost:44401/
      - REDIRECT_URI=http://localhost:44100/signincallback
      - POST_LOGOUT_REDIRECT_URI=http://localhost:44100/signoutcallback
      - ISSUER=http://localhost:44401
      - JWKS_URI=http://localhost:44401/.well-known/openid-configuration/jwks
      - AUTHORIZATION_ENDPOINT=http://localhost:44401/connect/authorize
      - TOKEN_ENDPOINT=http://localhost:44401/connect/token
      - USERINFO_ENDPOINT=http://localhost:44401/connect/userinfo
      - END_SESSION_ENDPOINT=http://localhost:44401/connect/endsession
      - CHECK_SESSION_IFRAME=http://localhost:44401/connect/checksession
      - REVOCATION_ENDPOINT=http://localhost:44401/connect/revocation
      - INTROSPECTION_ENDPOINT=http://localhost:44401/connect/introspect
      - DEVICE_AUTHORIZATION_ENDPOINT=http://localhost:44401/connect/deviceauthorization
      - STOCK_API=http://localhost:44405/
    depends_on:
      - stockmicroservices.api
      - stockmicroservices.identityserver
    ports:
      - "44100:80"

  stockmicroservices.stockwebstatusapi:
    ports:
      - "44610:5000"
    depends_on:
      - stockmicroservices.api
      - stockmicroservices.apigateway
      - stockmicroservices.identityserver
      - stockmicroservices.stockmarketupdater
      - stockmicroservices.webclient
    environment:
      SERVICE_LIST: >
        [
          {"name": "StockAPI", "url": "http://stockapi/hc"},
          {"name": "StockIdentityServer", "url": "http://stockidentityserver/hc"},
          {"name": "StockWebClient", "url": "http://stockwebclient/hc"},
          {"name": "StockMarketUpdater", "url": "http://stockmarketupdater:44444"},
          {"name": "StockApiGateway", "url": "http://stockapigateway/hc"}
        ]

  stockmicroservices.stockwebstatus:
    ports:
      - "44080:80"
    depends_on:
      - stockmicroservices.stockwebstatusapi
    environment:
      - WEBSTATUSAPI=http://localhost:44610/api/health-status
