version: '3.4'

services:
  otel-collector:
    image: ${DOCKER_REGISTRY-}otel-collector
    build:
      context: .
      dockerfile: opentelemetry/collector/Dockerfile

  tempo:
    image: ${DOCKER_REGISTRY-}tempo
    build:
      context: .
      dockerfile: opentelemetry/tempo/Dockerfile

  grafana:
    image: grafana/grafana:latest


  loki:
    image: ${DOCKER_REGISTRY-}loki
    build:
      context: .
      dockerfile: opentelemetry/loki/Dockerfile

  prometheus:
    image: prom/prometheus:latest

  envoy:
    image: ${DOCKER_REGISTRY-}envoy
    build:
      context: .
      dockerfile: Envoy/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management-alpine  

  stockmicroservices.stockmarketupdater:
    image: ${DOCKER_REGISTRY-}stockmarketupdater
    build:
      context: .
      dockerfile: StockMicroservices.StockMarketUpdater/Dockerfile

  stockmicroservices.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: StockMicroservices.API/Dockerfile


  stockmicroservices.apigateway:
    image: ${DOCKER_REGISTRY-}stockapigateway
    build:
      context: .
      dockerfile: StockMicroservices.APIGateway/Dockerfile


  stockmicroservices.identityserver:
    image: ${DOCKER_REGISTRY-}stockidentityserver
    build:
      context: .
      dockerfile: StockMicroservices.IdentityServer/Dockerfile


  stockmicroservices.webclient:
    image: ${DOCKER_REGISTRY-}stockwebclient
    build:
      context: .
      dockerfile: StockMicroservices.WebClient/ClientApp/Dockerfile

  stockmicroservices.stockwebstatusapi:
    image: ${DOCKER_REGISTRY-}stockwebstatusapi
    build:
      context: .
      dockerfile: stockwebstatusapi/Dockerfile

  stockmicroservices.stockwebstatus:
    image: ${DOCKER_REGISTRY-}stockwebstatus
    build:
      context: .
      dockerfile: stockwebstatus/Dockerfile

volumes:
  grafana-data:
  