apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.loki.servicePort }}
      targetPort: {{ .Values.loki.targetPort }}
  type: NodePort