apiVersion: apps/v1
kind: Deployment    
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelcollector.image }}
          ports:
            - containerPort: {{ .Values.otelcollector.targetPort1 }}
            - containerPort: {{ .Values.otelcollector.targetPort2 }}
            - containerPort: {{ .Values.otelcollector.targetPort3 }}