apiVersion: v1
kind: Secret
metadata:
  name: stocktrader-secrets
type: Opaque
data:
  rabbitmq-username: {{ .Values.configMap.rabbitMq.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.configMap.rabbitMq.password | b64enc | quote }}
