apiVersion: v1
kind: Service
metadata:
  name: stockidentityserver
spec:
  selector:
    app: stockidentityserver
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.stockidentityserver.servicePort }}
      targetPort: {{ .Values.stockidentityserver.targetPort | default 80 }}
  type: NodePort