apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmarketupdater
spec:
  selector:
    matchLabels:
      app: stockmarketupdater
  template:
    metadata:
      labels:
        app: stockmarketupdater
    spec:
      containers:
      - name: stockmarketupdater
        image: {{ .Values.stockmarketupdater.image }}
        env:
          - name: RabbitMq__RetryCount
            value: {{ .Values.stockmarketupdater.retryCount | quote | default "5" }}
          - name: RabbitMq__Hostname
            value: rabbitmq
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: {{ .Values.rabbitmq.secretName }}
                key: rabbitmq-username
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: {{ .Values.rabbitmq.secretName }}
                key: rabbitmq-password
        ports:
        - containerPort: 44444
