apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: {{ .Values.tempo.image }}
          ports:
            - containerPort: {{ .Values.tempo.targetPort1 }}
            - containerPort: {{ .Values.tempo.targetPort2 }}