# Default values for stocktrader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configMap:
  enabled: true
  rabbitMq:
    username: "user"
    password: "password"
  data:
    stockwebclient_env: Development
    stockidentityserver_env: Development
    stockapigateway_env: Development
    identityserverurl: "http://stockidentityserver:44401"
    stockapi_env: Development
    stockapi_apiscope: StockMicroservicesAPI

  # This is for setting up the RabbitMQ configuration more information can be found here: https://www.rabbitmq.com/configure.html
rabbitmq:
  image: "rabbitmq:3-management-alpine"
  host: "rabbitmq"
  port1: 5672
  port2: 15672
  secretName: "stocktrader-secrets"

stockmarketupdater:
  image: "osahile/stockmarketupdater:1.0.0"
  retryCount: 5
  secretName: "stocktrader-secrets"
  hostname: "rabbitmq"
  port: 44444

stockapi:
  urls: "http://+:80"
  identityServerUrl: "http://stockidentityserver"
  otlp:
    endpoint: "http://otel-collector:4318"
    serviceName: "StockMicroservicesAPI"
  targetPort: 80
  servicePort: 44300
  image: "osahile/stockapi:1.0.0"
  rabbitMq:
    retryCount: 5
    hostname: "rabbitmq"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

stockapigateway:
  targetPort: 80
  servicePort: 44405
  image: "osahile/envoy:1.0.1"


stockidentityserver:
  urls: "http://+"
  identityServerUrl: "http://stockidentityserver"
  image: "osahile/stockidentityserver:1.0.0"
  targetPort: 80
  servicePort: 44401
  
stockwebclient:
  image: "osahile/stockwebclient:1.0.0"
  replicaCount: 2
  target: 80
  servicePort: 44100
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    cpu:
      targetUtilizationPercentage: 70
    memory:
      targetUtilizationPercentage: 70
  identity:
    authority: "http://stockidentityserver/"
    redirect_uri: "http://stockwebclient/signincallback"
    client_id: "client_id_react3"
    post_logout_redirect_uri: "http://stockwebclient/signoutcallback"
    issuer: "http://stockidentityserver"
    jwks_uri: "http://stockidentityserver/.well-known/openid-configuration/jwks"
    authorization_endpoint: "http://stockidentityserver/connect/authorize"
    token_endpoint: "http://stockidentityserver/connect/token"
    userinfo_endpoint: "http://stockidentityserver/connect/userinfo"
    end_session_endpoint: "http://stockidentityserver/connect/endsession"
    check_session_iframe: "http://stockidentityserver/connect/checksession"
    revocation_endpoint: "http://stockidentityserver/connect/revocation"
    introspection_endpoint: "http://stockidentityserver/connect/introspect"
    device_authorization_endpoint: "http://stockidentityserver/connect/deviceauthorization"
  stockapi: "http://stockapigateway/api/"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
stockwebstatusapi:
  targetPort: 5000
  servicePort: 44610
  image: "osahile/stockwebstatusapi:1.0.0"
  service_list: [{"name": "StockAPI", "url": "http://stockapi:44300/hc"},{"name": "StockAPIGateway", "url": "http://stockapigateway:44405/hc"},{"name": "StockIdentityServer", "url": "http://stockidentityserver:44401/hc"},{"name": "StockMarketUpdater", "url": "http://stockmarketupdater:44444/hc"},{"name": "StockWebClient", "url": "http://stockwebclient:44100/hc"}]
stockwebstatus:
  targetPort: 80
  servicePort: 44080
  image: "osahile/stockwebstatus:1.0.0"
  webStatusApiUrl: "http://stockwebstatusapi/api/health-status"

otelcollector:
  image: "osahile/otel-collector:1.0.0"
  targetPort1: 4317
  targetPort2: 4318
  targetPort3: 7777
  servicePort1: 4317
  servicePort2: 4318
  servicePort3: 7777

tempo:
  image: "osahile/tempo:1.0.0"
  targetPort1: 3200
  targetPort2: 7778
  servicePort1: 3200
  servicePort2: 7778

grafana:
  image: "grafana/grafana:latest"
  targetPort: 3000
  servicePort: 3000

loki:
  image: "osahile/loki:1.0.0"
  targetPort: 3100
  servicePort: 3100

prometheus:
  image: "osahile/prometheus:1.0.0"
  targetPort: 9090
  servicePort: 9090

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  #annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: stockwebclient
      paths:
        - path: /
          pathType: Prefix
          name: stockwebclient
          port: 44100
    - host: stockwebstatus
      paths:
        - path: /
          pathType: Prefix
          name: stockwebstatus
          port: 44080
    - host: stockidentityserver
      paths:
        - path: /
          pathType: Prefix
          name: stockidentityserver
          port: 44401
    - host: stockapi
      paths:
        - path: /api
          pathType: Prefix
          name: stockapi
          port: 44300
    - host: stockwebstatusapi
      paths:
        - path: /
          pathType: Prefix
          name: stockwebstatusapi
          port: 44610
    - host: stockmarketupdater
      paths:
        - path: /
          pathType: Prefix
          name: stockmarketupdater
          port: 44444
    - host: stockapigateway
      paths:
        - path: /api
          pathType: Prefix
          name: stockapigateway
          port: 44405
    - host: grafana
      paths:
        - path: /
          pathType: Prefix
          name: grafana
          port: 3000
    - host: prometheus
      paths:
        - path: /
          pathType: Prefix
          name: prometheus
          port: 9090
        - path: /api
          pathType: Prefix
          name: prometheus
          port: 9090

  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
