apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-config
data:
  stockwebclient_env: Development
  stockidentityserver_env: Development
  stockapigateway_env: Development
  identityserverurl: http://stockidentityserver:44401
  stockapi_env: Development
  stockapi_apiscope: StockMicroservicesAPI
  mongo_hostname: mongo
  mongo_database: stocks

