apiVersion: v1
kind: Secret
metadata:
  name: stock-secret
type: Opaque
stringData:
  rabbitmq_password: password
  rabbitmq_user: user
  mongo_admin_user: root
  mongo_admin_password: admin1
  mongo_dbuser_user: steam
  mongo_dbuser_password: steam1
  mongo_connectionstring: mongodb://root:admin1@mongo:27017/
