apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockapi
spec:
  selector:
    matchLabels:
      app: stockapi
  template:
    metadata:
      labels:
        app: stockapi
    spec:
      containers:
      - name: stockapi
        image: osahile/stockapi
        env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: stock-config
                key: stockapi_env
          - name: APIScope
            valueFrom:
              configMapKeyRef:
                name: stock-config
                key: stockapi_apiscope
          - name: IdentityServerUrl
            valueFrom:
              configMapKeyRef:
                name: stock-config
                key: identityserverurl
          - name: RabbitMq__RetryCount
            value: '5'
          - name: RabbitMq__Hostname
            value: rabbitmq
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: rabbitmq_user
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: rabbitmq_password
          - name: Database__ConnectionString
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: mongo_connectionstring
          - name: Database__AdminUser
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: mongo_admin_user
          - name: Database__AdminPassword
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: mongo_admin_password
          - name: Database__DbUser
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: mongo_dbuser_user
          - name: Database__DbPassword
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: mongo_dbuser_password
          - name: Database__Hostname
            valueFrom:
              configMapKeyRef:
                name: stock-config
                key: mongo_hostname
          - name: Database__Name
            valueFrom:
              configMapKeyRef:
                name: stock-config
                key: mongo_database
        ports:
        - containerPort: 80
