#!/bin/sh

echo "Generating config.json..."

cat <<EOF > /usr/share/nginx/html/config.json
{
  "AUTHORITY": "${AUTHORITY}",
  "REDIRECT_URI": "${REDIRECT_URI}",
  "POST_LOGOUT_REDIRECT_URI": "${POST_LOGOUT_REDIRECT_URI}",
  "ISSUER": "${ISSUER}",
  "JWKS_URI": "${JWKS_URI}",
  "AUTHORIZATION_ENDPOINT": "${AUTHORIZATION_ENDPOINT}",
  "TOKEN_ENDPOINT": "${TOKEN_ENDPOINT}",
  "USERINFO_ENDPOINT": "${USERINFO_ENDPOINT}",
  "END_SESSION_ENDPOINT": "${END_SESSION_ENDPOINT}",
  "CHECK_SESSION_IFRAME": "${CHECK_SESSION_IFRAME}",
  "REVOCATION_ENDPOINT": "${REVOCATION_ENDPOINT}",
  "INTROSPECTION_ENDPOINT": "${INTROSPECTION_ENDPOINT}",
  "DEVICE_AUTHORIZATION_ENDPOINT": "${DEVICE_AUTHORIZATION_ENDPOINT}",
  "STOCK_API": "${STOCK_API}"
}
EOF

exec "$@"
